2017-12-12 16:20:02 Error: [Cake\Routing\Exception\MissingControllerException] Controller class CakePHP could not be found.
Exception Attributes: array (
  'class' => 'CakePHP',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/cakePHP/
Stack Trace:
#0 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-12 16:24:55 Error: [Cake\Controller\Exception\MissingActionException] Action CakePHPController::index() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CakePHPController',
  'action' => 'index',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp/cakePHP/
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-12 16:25:48 Error: [Cake\View\Exception\MissingTemplateException] Template file "CakePHP\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'CakePHP\\index.ctp',
)
Request URL: /cakephp/cakePHP/
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('CakePHP\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-13 14:05:49 Error: [Cake\Controller\Exception\MissingActionException] Action CakePHPController::client() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CakePHPController',
  'action' => 'client',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp/cakePHP/client
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-13 14:06:43 Error: [Cake\Controller\Exception\MissingActionException] Action CakePHPController::clients() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CakePHPController',
  'action' => 'clients',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp/cakePHP/clients
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-13 14:11:26 Error: [Cake\Controller\Exception\MissingActionException] Action ClientsController::view() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ClientsController',
  'action' => 'view',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-13 14:12:47 Error: [Cake\View\Exception\MissingTemplateException] Template file "Clients\view.ctp" is missing.
Exception Attributes: array (
  'file' => 'Clients\\view.ctp',
)
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Clients\\view')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-13 14:13:59 Error: [Cake\Controller\Exception\MissingActionException] Action CakePHPController::clients() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'CakePHPController',
  'action' => 'clients',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /cakephp/cakePHP/clients
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\CakePHPController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-13 14:21:41 Error: [Cake\View\Exception\MissingHelperException] Helper class prenomHelper could not be found.
Exception Attributes: array (
  'class' => 'prenomHelper',
  'plugin' => NULL,
)
Request URL: /clients/
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php(91): Cake\View\HelperRegistry->_throwMissingClassError('prenom', NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\HelperRegistry.php(66): Cake\Core\ObjectRegistry->load('prenom')
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(866): Cake\View\HelperRegistry->__isset('prenom')
#3 C:\wamp64\www\cakephp\src\Template\Clients\index.ctp(15): Cake\View\View->__get('prenom')
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(970): include('C:\\wamp64\\www\\c...')
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(930): Cake\View\View->_evaluate('C:\\wamp64\\www\\c...', Array)
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(578): Cake\View\View->_render('C:\\wamp64\\www\\c...')
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#10 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#11 {main}


2017-12-13 14:57:25 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Clients.slug' in 'where clause'
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(871): Cake\Database\Query->execute()
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(216): Cake\ORM\Query->_execute()
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(822): Cake\ORM\Query->_all()
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(339): Cake\ORM\Query->all()
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(350): Cake\ORM\Query->first()
#10 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#11 [internal function]: App\Controller\ClientsController->view()
#12 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#15 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-13 15:04:15 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Clients.slug' in 'where clause'
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(871): Cake\Database\Query->execute()
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(216): Cake\ORM\Query->_execute()
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(822): Cake\ORM\Query->_all()
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(339): Cake\ORM\Query->all()
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(350): Cake\ORM\Query->first()
#10 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#11 [internal function]: App\Controller\ClientsController->view()
#12 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#15 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-13 15:04:33 Error: [PDOException] SQLSTATE[42S22]: Column not found: 1054 Unknown column 'Clients.slug' in 'where clause'
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(871): Cake\Database\Query->execute()
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(216): Cake\ORM\Query->_execute()
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(822): Cake\ORM\Query->_all()
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(339): Cake\ORM\Query->all()
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Datasource\QueryTrait.php(350): Cake\ORM\Query->first()
#10 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#11 [internal function]: App\Controller\ClientsController->view()
#12 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#15 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-13 15:06:58 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "clients"
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\ClientsController->view()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:07:53 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "clients"
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\ClientsController->view()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:08:04 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "clients"
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\ClientsController->view()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:08:39 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "clients"
Request URL: /clients/view
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(18): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\ClientsController->view()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-13 15:09:08 Error: [Cake\Controller\Exception\MissingActionException] Action ClientsController::edit() could not be found, or is not accessible.
Exception Attributes: array (
  'controller' => 'ClientsController',
  'action' => 'edit',
  'prefix' => '',
  'plugin' => NULL,
)
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#2 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#3 {main}


2017-12-13 15:12:43 Error: [Cake\View\Exception\MissingTemplateException] Template file "Clients\edit.ctp" is missing.
Exception Attributes: array (
  'file' => 'Clients\\edit.ctp',
)
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Clients\\edit')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-13 18:57:28 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 18:57:29 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 18:57:55 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 18:57:55 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-13 21:22:54 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-13 21:22:56 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 05:48:02 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 05:48:03 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 05:56:03 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 05:56:04 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:06:33 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:06:34 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:08:23 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Src could not be found.
Exception Attributes: array (
  'class' => 'Src',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /cakephp/src/Template/Clients/add.ctp
Stack Trace:
#0 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-14 06:09:44 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:09:45 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:10:04 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:10:05 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:11:11 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:11:12 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:12:31 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:12:32 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:13:26 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:13:27 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:13:35 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:13:36 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add/5
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:13:47 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:13:48 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:14:09 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:14:10 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:16:27 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:16:28 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:53:05 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:53:06 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:54:13 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:54:13 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:57:39 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:57:40 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:57:42 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:57:42 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 06:58:04 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 06:58:05 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:05:35 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(41): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:10:00 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(41): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:10:19 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:10:19 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:11:40 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(41): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:12:37 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(41): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:12:49 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(41): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:15:16 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(41): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:22:47 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(44): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:23:48 Warning: Warning (2): Attempt to assign property of non-object in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 45]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 45
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 07:23:48 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:23:49 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:24:55 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:24:56 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:25:16 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:25:17 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:27:16 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:27:17 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:29:01 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:29:02 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:29:04 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:29:04 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:29:10 Warning: Warning (2): Missing argument 1 for App\Controller\ClientsController::edit() in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 26]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::edit() - APP/Controller\ClientsController.php, line 26
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 07:29:11 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "clients"
Request URL: /clients/edit/
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(28): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\ClientsController->edit()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:30:59 Error: [Cake\Datasource\Exception\RecordNotFoundException] Record not found in table "clients"
Request URL: /clients/edit/2
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(28): Cake\ORM\Query->firstOrFail()
#1 [internal function]: App\Controller\ClientsController->edit('2')
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 07:31:18 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:31:19 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:31:40 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:31:40 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:31:42 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:31:42 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:34:41 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:34:42 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 07:55:00 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 07:55:01 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 08:23:38 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 08:23:39 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 08:23:53 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 08:23:54 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 08:25:53 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(44): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 08:29:17 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 08:29:17 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 08:46:30 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Services could not be found.
Exception Attributes: array (
  'class' => 'Services',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /services
Stack Trace:
#0 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-14 08:49:09 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Services could not be found.
Exception Attributes: array (
  'class' => 'Services',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /services
Stack Trace:
#0 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-14 08:51:48 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 08:51:49 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:02:24 Error: [Cake\Routing\Exception\MissingControllerException] Controller class Service could not be found.
Exception Attributes: array (
  'class' => 'Service',
  'plugin' => NULL,
  'prefix' => NULL,
  '_ext' => NULL,
)
Request URL: /service
Stack Trace:
#0 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#1 {main}


2017-12-14 09:02:42 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:02:43 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:04:28 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:04:29 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:09:40 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:09:41 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:09:43 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:09:43 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:11:19 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:11:19 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:24:18 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:24:26 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:27:17 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:27:17 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:30:57 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 09:30:58 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 09:32:17 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\index.ctp',
)
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Services\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-14 09:33:03 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\index.ctp',
)
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Services\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-14 09:34:21 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\index.ctp',
)
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Services\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-14 09:35:34 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\index.ctp',
)
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Services\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-14 09:35:40 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\index.ctp',
)
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Services\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-14 09:46:34 Error: [Cake\View\Exception\MissingTemplateException] Template file "Services\index.ctp" is missing.
Exception Attributes: array (
  'file' => 'Services\\index.ctp',
)
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\View\View.php(575): Cake\View\View->_getViewFileName('Services\\index')
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(598): Cake\View\View->render(NULL, NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(120): Cake\Controller\Controller->render()
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ServicesController))
#4 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#5 {main}


2017-12-14 10:33:41 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 10:33:41 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 10:42:21 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 10:42:22 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 10:42:25 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 10:42:26 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 10:44:41 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 10:44:42 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:00:45 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:00:46 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:01:07 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:01:08 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:01:42 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:01:43 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:01:48 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:01:49 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:09:23 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:09:25 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:09:58 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:09:58 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:10:02 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:10:02 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:13:14 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:13:15 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:17:13 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 11:17:13 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 11:21:45 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(44): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 11:51:18 Warning: Warning (2): Missing argument 1 for Cake\ORM\Query::find(), called in C:\wamp64\www\cakephp\src\Controller\ClientsController.php on line 60 and defined in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php, line 938]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
Cake\ORM\Query::find() - CORE\src\ORM\Query.php, line 938
App\Controller\ClientsController::edit() - APP/Controller\ClientsController.php, line 60
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 11:51:19 Error: [BadMethodCallException] Unknown finder method "SELECT `clients`.`id` AS `clients__id`, `clients`.`nom` AS `clients__nom`, `clients`.`postnom` AS `clients__postnom`, `clients`.`prenom` AS `clients__prenom`, `clients`.`telephone` AS `clients__telephone`, `clients`.`email` AS `clients__email`, `clients`.`adresse` AS `clients__adresse`, `clients`.`cree` AS `clients__cree`, `clients`.`modifie` AS `clients__modifie` FROM `clients` `clients` WHERE `id` = :c0"
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(933): Cake\ORM\Table->callFinder(Object(Cake\ORM\Query), Object(Cake\ORM\Query), Array)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1758): Cake\ORM\Table->find(Object(Cake\ORM\Query), Array)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Query.php(940): Cake\ORM\Table->callFinder(NULL, Object(Cake\ORM\Query), Array)
#3 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(60): Cake\ORM\Query->find()
#4 [internal function]: App\Controller\ClientsController->edit('1')
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#8 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#9 {main}


2017-12-14 12:02:24 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 12:02:24 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 12:02:30 Warning: Warning (2): Missing argument 1 for App\Controller\ClientsController::edit() in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 42]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::edit() - APP/Controller\ClientsController.php, line 42
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 12:12:27 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1597): Cake\Database\Query->execute()
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1448): Cake\ORM\Table->_update(Object(Cake\ORM\Entity), Array)
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(53): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\ClientsController->edit('1')
#12 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#15 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-14 12:14:03 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1597): Cake\Database\Query->execute()
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1448): Cake\ORM\Table->_update(Object(Cake\ORM\Entity), Array)
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(53): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\ClientsController->edit('1')
#12 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#15 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-14 12:15:09 Error: [PDOException] SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'email' cannot be null
Request URL: /clients/edit/1
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\MysqlStatement.php(36): PDOStatement->execute(NULL)
#1 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Statement\StatementDecorator.php(169): Cake\Database\Statement\MysqlStatement->execute(NULL)
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Log\LoggingStatement.php(55): Cake\Database\Statement\StatementDecorator->execute(NULL)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(270): Cake\Database\Log\LoggingStatement->execute()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Query.php(174): Cake\Database\Connection->run(Object(Cake\ORM\Query))
#5 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1597): Cake\Database\Query->execute()
#6 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1448): Cake\ORM\Table->_update(Object(Cake\ORM\Entity), Array)
#7 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1377): Cake\ORM\Table->_processSave(Object(Cake\ORM\Entity), Object(ArrayObject))
#8 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Database\Connection.php(546): Cake\ORM\Table->Cake\ORM\{closure}(Object(Cake\Database\Connection))
#9 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\ORM\Table.php(1378): Cake\Database\Connection->transactional(Object(Closure))
#10 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(53): Cake\ORM\Table->save(Object(Cake\ORM\Entity))
#11 [internal function]: App\Controller\ClientsController->edit('1')
#12 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#13 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#14 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#15 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#16 {main}


2017-12-14 12:51:21 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(68): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 13:00:44 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 67]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 67
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 13:00:44 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:00:44 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:27:14 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:27:16 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of Error given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(Error))
#1 {main}
  thrown
Request URL: /cakephp/services
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:29:02 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 66]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 66
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 13:29:02 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:29:03 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:31:43 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 66]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 66
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 13:31:43 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:31:44 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:46:02 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 66]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 66
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 13:46:02 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:46:05 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:46:20 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 66]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 66
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 13:46:20 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:46:21 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:47:48 Error: [BadMethodCallException] Method getData does not exist
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\src\Controller\ClientsController.php(84): Cake\Network\Request->__call('getData', Array)
#1 [internal function]: App\Controller\ClientsController->add()
#2 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Controller\Controller.php(416): call_user_func_array(Array, Array)
#3 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(114): Cake\Controller\Controller->invokeAction()
#4 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Routing\Dispatcher.php(87): Cake\Routing\Dispatcher->_invoke(Object(App\Controller\ClientsController))
#5 C:\wamp64\www\cakephp\webroot\index.php(36): Cake\Routing\Dispatcher->dispatch(Object(Cake\Network\Request), Object(Cake\Network\Response))
#6 {main}


2017-12-14 13:48:42 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:48:43 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:49:16 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:49:16 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:49:33 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:49:34 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:49:59 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:50:00 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:50:30 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:50:31 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 13:50:44 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 13:50:44 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 14:07:24 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 92]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 92
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 14:07:24 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 14:07:25 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


2017-12-14 14:08:01 Warning: Warning (2): Creating default object from empty value in [C:\wamp64\www\cakephp\src\Controller\ClientsController.php, line 92]
Trace:
Cake\Error\BaseErrorHandler::handleError() - CORE\src\Error\BaseErrorHandler.php, line 138
App\Controller\ClientsController::add() - APP/Controller\ClientsController.php, line 92
Cake\Controller\Controller::invokeAction() - CORE\src\Controller\Controller.php, line 416
Cake\Routing\Dispatcher::_invoke() - CORE\src\Routing\Dispatcher.php, line 114
Cake\Routing\Dispatcher::dispatch() - CORE\src\Routing\Dispatcher.php, line 87
[main] - ROOT\webroot\index.php, line 36



2017-12-14 14:08:01 Error: Fatal Error (1): Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown in [C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php, line 153]
Trace:
Cake\Error\BaseErrorHandler::handleFatalError() - CORE\src\Error\BaseErrorHandler.php, line 191
Cake\Error\BaseErrorHandler::Cake\Error\{closure}() - CORE\src\Error\BaseErrorHandler.php, line 89
[main] - [internal], line ??



2017-12-14 14:08:01 Error: [Cake\Error\FatalErrorException] Uncaught TypeError: Argument 1 passed to Cake\Error\BaseErrorHandler::handleException() must be an instance of Exception, instance of TypeError given in C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php:153
Stack trace:
#0 [internal function]: Cake\Error\BaseErrorHandler->handleException(Object(TypeError))
#1 {main}
  thrown
Request URL: /clients/add
Stack Trace:
#0 C:\wamp64\www\cakephp\vendor\cakephp\cakephp\src\Error\BaseErrorHandler.php(89): Cake\Error\BaseErrorHandler->handleFatalError(1, 'Uncaught TypeEr...', 'C:\\wamp64\\www\\c...', 153)
#1 [internal function]: Cake\Error\BaseErrorHandler->Cake\Error\{closure}()
#2 {main}


